#!/bin/sh
mvn clean package
docker build -t maniyatailor/HotelApplication .
docker rm -f HotelApplication 2>/dev/null || true
docker run -it --name HotelApplication -p 8080:8080 --name HotelApplication maniyatailor/HotelApplication
